### ISSUE TITLE
Support unsigned 64-bit integers for sequence numbers

### ISSUE THREAD

**Issue by JohnGreenan** [ferrumfix/ferrumfix#108]
Is your feature request related to a problem? Please describe.
Per https://www.fixtrading.org/groups/continuousmkts/
Sequence number resets are a bore.

Describe the solution you'd like
The implementation proposed is to use an unsigned 64 bit integer for a sequence number.

Using 1 billion sequence numbers per second, that will last for 584 years until they run out.

So we can leave the problem to our great, great, great (more) grandchildren to solve!

Describe alternatives you've considered
![delete_me](https://user-images.githubusercontent.com/8924979/225230500-24d445f2-e776-4d0c-a87b-33b8000fe854.jpg)

See attached "Continuous Markets WG- 24x7 FIX Best Practise Working Draft_v0.015.docx"
[Continuous Markets WG- 24x7 FIX Best Practise Working Draft_v0.015.docx](https://github.com/ferrumfix/ferrumfix/files/10976811/Continuous.Markets.WG-.24x7.FIX.Best.Practise.Working.Draft_v0.015.docx)

It looks like the use of usize for the datatype of BeginSeqNum and EndSeqNum in ResendRequest message means that these are 64 bit unsigned integers if complied on any modern 64-bit architecture.

Can you confirm this understanding is correct, that there is no need to change ferrumfix?

**Comment by JohnGreenan** [comment]
See also 
https://github.com/da4089/simplefix/issues/50
https://github.com/quickfix-j/quickfixj/issues/621
https://github.com/quickfix/quickfix/issues/419
https://github.com/ferrumfix/ferrumfix/issues/108
https://github.com/connamara/quickfixn/issues/760

**Comment by neysofu** [comment]
This is correct, FerrumFIX has support for 64-bit sequence numbers (in fact, it doesn't support anything other than 64-bit counters)!
