### ISSUE TITLE
Some tag-value messages seem to break internal state of a `Decoder` on `fefix v0.7.0`

### ISSUE THREAD

**Issue by gsnoff** [ferrumfix/ferrumfix#17]
Consider this example test function:

```Rust
#[test]
fn decode() {
    use fefix::{definitions::fix44, prelude::*, tagvalue::{Config, Decoder}};
    const SAMPLES: [&[u8]; 2] = [
        b"8=FIX.4.4\x019=176\x0135=X\x0149=ERISX\x0156=XXXXXXXXX\x0134=3\x01\
        52=20220714-09:26:22.518\x01262=TEST-220714092622-EfkcibvXPhF34SVNQYwwRz\x01\
        60=20220714-09:26:22.517712684\x016006=0\x01268=1\x01279=0\x01269=J\x01\
        55=BTC/USD\x0115=BTC\x0110=051\x01",

        b"8=FIX.4.4\x019=227\x0135=f\x0149=ERISX\x0156=XXXXXXXXX\x0134=4\x01\
        52=20220714-09:26:22.518\x01324=TEST-220714092622-EfkcibvXPhF34SVNQYwwRz\x01\
        60=20220714-09:26:22.517712684\x0155=BTC/USD\x01460=2\x01107=BTC/USD\x016006=0\x01\
        15=BTC\x01326=17\x01969=0.1\x01562=0.0001\x011140=100000\x01561=0.000001\x0110=248\x01",
    ];
    let mut decoder = Decoder::<Config>::new(Dictionary::fix44());
    for sample in SAMPLES {
        let message = decoder.decode(sample)
            .expect("Couldn't decode sample FIX message");
        let msg_type = message.fv::<fix44::MsgType>(fix44::MSG_TYPE);
        assert!(msg_type.is_ok(), "fv() returns {:?}", msg_type);
    }
}
```

When compiled with crate `fefix` version 0.7.0, it fails with the following message:

```
thread 'decode' panicked at 'fv() returns Err(None)', [PATH]:[LINE]:[COLUMN]
```

Interestingly enough, each of the samples succeeds when passed through a separate `Decoder` instance solo. However when they’re passed in the given sequence to a single `Decoder`, random access to any of the fields of the second message (as well as of any other messages to follow it) will fail.

**Comment by neysofu** [comment]
Thanks for the bug report.

Are the checksums correct? Once I bypass checksums verification, I'm hitting the same error as you did both on `v0.7.0` as well as latest `master`.

**Comment by neysofu** [comment]
Fix is out and will be included in `v0.8.0`. Most of the recent bugs -this one included- originated in a fragile and badly written part of the code, which I'll hopefully get around to rewriting soon.

**Comment by gsnoff** [comment]
@neysofu 
> Are the checksums correct? Once I bypass checksums verification, I'm hitting the same error as you did both on v0.7.0 as well as latest master.

Sorry, I had to change the `TargetCompID (56)` field contents for security reasons, and forgot about checksums. I’ve updated the original post now.

**Comment by neysofu** [comment]
Thanks, no worries! I'll go ahead and close this :)
